version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=redis
      - S3_BUCKET=moritalous-firefox-send
      - FXA_REQUIRED=false
  redis:
    image: redis:alpine
    volumes:
      - /data/redis:/data
